### ISSUE TITLE
local Tox tests are broken

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/zope.formlib#28]
While Travis seems to be green ( https://travis-ci.org/zopefoundation/zope.formlib ), local tests run by Tox locally are broken.

Tests on Tox are green when checking out the last commit before @d-maurer s merged pull request. - ie 2554e876acbe342d86c3f92b85f5305ce316cf44 is still good.

```
zope.formlib on  master via 🐍 v2.7.17 took 2s 
❯ tox -e=py37
GLOB sdist-make: /home/jugmac00/Projects/zope.formlib/setup.py
py37 inst-nodeps: /home/jugmac00/Projects/zope.formlib/.tox/.tmp/package/1/zope.formlib-4.7.0.dev0.zip
py37 installed: python-gettext==4.0,pytz==2019.3,six==1.14.0,transaction==3.0.0,zope.browser==2.3,zope.browserpage==4.4.0,zope.browserresource==4.4,zope.component==4.6,zope.configuration==4.3.1,zope.contenttype==4.5.0,zope.datetime==4.2.0,zope.deferredimport==4.3.1,zope.deprecation==4.4.0,zope.event==4.4,zope.exceptions==4.3,zope.formlib==4.7.0.dev0,zope.hookable==5.0.0,zope.i18n==4.7.0,zope.i18nmessageid==5.0.0,zope.interface==4.7.1,zope.lifecycleevent==4.3,zope.location==4.2,zope.pagetemplate==4.5.0,zope.proxy==4.3.3,zope.publisher==5.1.1,zope.schema==4.9.3,zope.security==5.1.0,zope.tal==4.4,zope.tales==5.0.1,zope.testing==4.7,zope.testrunner==5.1,zope.traversing==4.3.1
py37 run-test-pre: PYTHONHASHSEED='1582797600'
py37 run-test: commands[0] | zope-testrunner --test-path=src
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.


Error in test test_edit (zope.formlib.tests.test_functional_objectwidget.Test)
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.7/unittest/case.py", line 624, in run
    self.setUp()
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/formlib/tests/test_functional_objectwidget.py", line 56, in setUp
    zope.formlib)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 657, in file
    include(context, name, package)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 471, in EndElement
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/config.py", line 868, in finish
    actions = self.handler(context, **args)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/browserresource/metaconfigure.py", line 112, in resourceDirectory
    "Directory %s does not exist" % directory
zope.configuration.exceptions.ConfigurationError: Directory /home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/formlib/js does not exist
    File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/formlib/configure.zcml", line 606.2-608.21



Error in test test_new (zope.formlib.tests.test_functional_objectwidget.Test)
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.7/unittest/case.py", line 624, in run
    self.setUp()
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/formlib/tests/test_functional_objectwidget.py", line 56, in setUp
    zope.formlib)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 657, in file
    include(context, name, package)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 471, in EndElement
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/config.py", line 868, in finish
    actions = self.handler(context, **args)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/browserresource/metaconfigure.py", line 112, in resourceDirectory
    "Directory %s does not exist" % directory
zope.configuration.exceptions.ConfigurationError: Directory /home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/formlib/js does not exist
    File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/formlib/configure.zcml", line 606.2-608.21



Error in test Tests (zope.formlib.tests.test_registrations)
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.7/unittest/case.py", line 624, in run
    self.setUp()
  File "/usr/lib/python3.7/doctest.py", line 2164, in setUp
    self._dt_setUp(test)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/formlib/tests/test_registrations.py", line 58, in setUp
    zope.formlib)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 657, in file
    include(context, name, package)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 471, in EndElement
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/config.py", line 868, in finish
    actions = self.handler(context, **args)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 471, in EndElement
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/configuration/config.py", line 868, in finish
    actions = self.handler(context, **args)
  File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/browserresource/metaconfigure.py", line 112, in resourceDirectory
    "Directory %s does not exist" % directory
zope.configuration.exceptions.ConfigurationError: Directory /home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/formlib/js does not exist
    File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/formlib/tests/registerWidgets.zcml", line 8.4-8.60
    File "/home/jugmac00/Projects/zope.formlib/.tox/py37/lib/python3.7/site-packages/zope/formlib/configure.zcml", line 606.2-608.21

  Ran 404 tests with 0 failures, 3 errors and 0 skipped in 1.013 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
ERROR: InvocationError for command /home/jugmac00/Projects/zope.formlib/.tox/py37/bin/zope-testrunner --test-path=src (exited with code 1)
_______________________________________________________________________________ summary _______________________________________________________________________________
ERROR:   py37: commands failed

zope.formlib on  master via 🐍 v2.7.17 took 3s 
```

**Comment by mgedmin** [comment]
I can reproduce it.

`tox --develop` works fine.

Looks like the problem is that the new js files are not copied over when you install the package.  check-manifest complains too.  If I fix MANIFEST.in, tox starts working again.

**Comment by jugmac00** [comment]
That's why https://github.com/mgedmin/check-manifest as a pre-commit hook is a darn good idea :-)

**Comment by d-maurer** [comment]
The `js` directory is in the git repository. In principle, it is the task of `setuptools.setup` (called with `package_data=True`) to make data available for installations. I have seen corresponding failures when the Python installation lacked the appropriate setuptools/"Source Code Control System" integration module (likely `setuptools_git` in this case).
